#!/usr/bin/env python3
"""gen_log_events.py -- generate the log event tables from shared/log/events.csv.

ADR-0023 D9 / REQ-LOG-012: events.csv is the single source of truth. This script
emits BOTH sides from it:

    shared/log/include/log_events.h   the C enum the firmware logs against
    host_tools/lib/log_events.py      the table the host decoder renders with

Why generated rather than hand-maintained in two languages: a drifted decoder
does not fail loudly, it renders the wrong event name for the right ID. That is
a confidently WRONG test result -- the worst failure mode a merge gate can have
(see docs/briefs/BVT-bench-brief.md, "the tester can lie").

Usage:
    python host_tools/gen_log_events.py            # write both files
    python host_tools/gen_log_events.py --check    # exit 1 if either is stale
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "shared" / "log" / "events.csv"
H_PATH = ROOT / "shared" / "log" / "include" / "log_events.h"
PY_PATH = ROOT / "host_tools" / "lib" / "log_events.py"

DIAG_BASE = 0x1000

BANNER = "/* GENERATED by host_tools/gen_log_events.py from shared/log/events.csv."
PY_BANNER = "# GENERATED by host_tools/gen_log_events.py from shared/log/events.csv."


class Event:
    __slots__ = ("id", "name", "cls", "arg0", "arg1", "desc")

    def __init__(self, id_: int, name: str, cls: str, arg0: str, arg1: str, desc: str):
        self.id, self.name, self.cls = id_, name, cls
        self.arg0, self.arg1, self.desc = arg0, arg1, desc


def load(csv_path: Path) -> list[Event]:
    events: list[Event] = []
    seen_ids: dict[int, str] = {}
    seen_names: set[str] = set()

    with open(csv_path, newline="", encoding="utf-8") as f:
        for lineno, row in enumerate(csv.reader(f), 1):
            if not row or row[0].lstrip().startswith("#") or not row[0].strip():
                continue
            if len(row) < 6:
                raise SystemExit(f"{csv_path}:{lineno}: expected 6 columns, got {len(row)}")

            id_str, name, cls, arg0, arg1, desc = (c.strip() for c in row[:6])
            try:
                id_ = int(id_str, 0)
            except ValueError:
                raise SystemExit(f"{csv_path}:{lineno}: bad id {id_str!r}") from None

            # IDs and names are a wire contract: a duplicate silently shadows the
            # other in one language and not the other.
            if id_ in seen_ids:
                raise SystemExit(f"{csv_path}:{lineno}: id {id_:#06x} already used by {seen_ids[id_]}")
            if name in seen_names:
                raise SystemExit(f"{csv_path}:{lineno}: duplicate name {name}")

            if cls not in ("contract", "diagnostic"):
                raise SystemExit(f"{csv_path}:{lineno}: class must be contract|diagnostic, got {cls!r}")

            # The class IS the ID range (REQ-LOG-008) -- if the two disagree, the
            # rule stops being mechanical and becomes a judgement call again.
            expect = "diagnostic" if id_ >= DIAG_BASE else "contract"
            if cls != expect:
                raise SystemExit(
                    f"{csv_path}:{lineno}: {name} is {cls} but id {id_:#06x} is in the "
                    f"{expect} range (< {DIAG_BASE:#06x} = contract)"
                )

            events.append(Event(id_, name, cls, arg0, arg1, desc))
            seen_ids[id_] = name
            seen_names.add(name)

    if not events:
        raise SystemExit(f"{csv_path}: no events found")
    return events


def render_h(events: list[Event]) -> str:
    out = [
        BANNER,
        " * DO NOT EDIT -- edit the CSV and re-run the generator (ADR-0023 D9). */",
        "#ifndef LOG_EVENTS_H",
        "#define LOG_EVENTS_H",
        "",
        "#include <stdint.h>",
        "",
        "/* Contract events (id < LOG_EVT_DIAG_BASE) are part of the tested interface:",
        " * a BVT test may assert on them, and changing one is a breaking change that",
        " * must update the affected tests in the same commit. Diagnostic events are",
        " * never asserted on and stay free to add, reword or delete (REQ-LOG-008). */",
        "",
    ]
    width = max(len(e.name) for e in events)
    for e in events:
        out.append(f"#define {e.name:<{width}} 0x{e.id:04X}U   /* {e.cls}: {e.desc} */")
    out += ["", "#endif /* LOG_EVENTS_H */", ""]
    return "\n".join(out)


def render_py(events: list[Event]) -> str:
    out = [
        PY_BANNER,
        "# DO NOT EDIT -- edit the CSV and re-run the generator (ADR-0023 D9).",
        '"""Event table for the host log decoder."""',
        "",
        "CONTRACT_MAX = 0x0FFF",
        "",
        "# id -> (name, class, arg0 meaning, arg1 meaning, description)",
        "EVENTS = {",
    ]
    for e in events:
        out.append(
            f"    0x{e.id:04X}: ({e.name!r}, {e.cls!r}, {e.arg0!r}, {e.arg1!r}, {e.desc!r}),"
        )
    out += [
        "}",
        "",
        "NAME_TO_ID = {v[0]: k for k, v in EVENTS.items()}",
        "",
        "",
        "def name(evt_id):",
        '    """Event name, or a hex placeholder for an id this build does not know."""',
        "    e = EVENTS.get(evt_id)",
        "    return e[0] if e else f'EVT_{evt_id:#06x}'",
        "",
        "",
        "def is_contract(evt_id):",
        '    """True if a test is allowed to assert on this event (REQ-LOG-008)."""',
        "    return evt_id <= CONTRACT_MAX",
        "",
    ]
    return "\n".join(out)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    """Returns True if the file is up to date (or was written)."""
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return True
    if check:
        what = "missing" if existing is None else "stale"
        print(f"{path.relative_to(ROOT)}: {what} -- re-run host_tools/gen_log_events.py",
              file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify the generated files are current; exit 1 if not")
    args = ap.parse_args()

    events = load(CSV_PATH)
    ok = write_or_check(H_PATH, render_h(events), args.check)
    ok = write_or_check(PY_PATH, render_py(events), args.check) and ok

    if args.check and ok:
        print(f"log events up to date ({len(events)} events)")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
