#!/usr/bin/env python3
"""gen_dev_key.py — generate the M4 dev signing keypair (ADR-0019 D1/D2).

Emits two artifacts from one P-256 keypair:
  * the PRIVATE key as a PEM (build-host secret, feeds sign_image.py --key) —
    NEVER committed / never on the device;
  * the PUBLIC key as a C header (X||Y, 64 bytes big-endian) for the CM0+
    keystore (ADR-0019 D2 — the key is compiled into the M0+ image).

This is a DEV key for bench bring-up, not a production/HSM key. Rotating it =
re-run this + rebuild the CM0+ image (ADR-0019 D2's "rotate = rebuild the
ROM-verified image" lifecycle).

Usage:
    python host_tools/gen_dev_key.py \\
        --out-priv ec_p256_dev_private.pem \\
        --out-header node_a_gateway/bootloader/proj_cm0p/src/crypto_pubkey_dev.h \\
        --key-id 1
"""
from __future__ import annotations

import argparse
import textwrap


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out-priv", required=True, help="private key PEM to write (host secret)")
    ap.add_argument("--out-header", required=True, help="C header for the CM0+ public key")
    ap.add_argument("--key-id", type=lambda x: int(x, 0), default=1, help="key_id for this key")
    args = ap.parse_args(argv)

    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import ec

    priv = ec.generate_private_key(ec.SECP256R1())

    pem = priv.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    with open(args.out_priv, "wb") as f:
        f.write(pem)

    nums = priv.public_key().public_numbers()
    x = nums.x.to_bytes(32, "big")
    y = nums.y.to_bytes(32, "big")
    xy = x + y  # 64 bytes, X||Y, big-endian (SEC1 uncompressed, sans 0x04 prefix)

    rows = textwrap.indent(
        "\n".join(
            ", ".join(f"0x{b:02X}u" for b in xy[i:i + 8]) + ","
            for i in range(0, len(xy), 8)
        ),
        "    ",
    )
    header = f"""\
/*
 * crypto_pubkey_dev.h — GENERATED by host_tools/gen_dev_key.py. DO NOT hand-edit.
 *
 * Dev P-256 public key (X||Y, big-endian, 64 B) for the CM0+ keystore
 * (ADR-0019 D2). Its private counterpart is the PEM you passed to --out-priv;
 * keep that off the device and out of git. Regenerate to rotate.
 */
#ifndef CRYPTO_PUBKEY_DEV_H
#define CRYPTO_PUBKEY_DEV_H

#include <stdint.h>

#define CRYPTO_DEV_KEY_ID   {args.key_id}u

static const uint8_t crypto_pubkey_dev[64] = {{
{rows}
}};

#endif /* CRYPTO_PUBKEY_DEV_H */
"""
    with open(args.out_header, "w", newline="\n") as f:
        f.write(header)

    print(f"wrote private key -> {args.out_priv}  (KEEP SECRET, do not commit)")
    print(f"wrote public key  -> {args.out_header}  (key_id={args.key_id})")
    print("next: sign an image with  python host_tools/sign_image.py <in> <out> "
          f"--key {args.out_priv} --key-id {args.key_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
