#!/usr/bin/env python3
"""make_test_image.py — build the M4 Seam-3 bench images as a C header.

Emits three signed test images the FBL can verify on-board, so one flash covers
all the cases that matter:
  * test_image_good     — correctly signed by the dev key   -> expect VALID
  * test_image_tampered — good image with one covered byte flipped after signing
                          -> expect INVALID (stage-1 hash mismatch)
  * test_image_wrongkey — signed by a DIFFERENT key but claiming the same key_id
                          -> expect INVALID (signature fails, proves it gates)

Usage (from the repo root, needs `cryptography` + the dev private key from
gen_dev_key.py):
    python host_tools/make_test_image.py \\
        --key ec_p256_dev_private.pem --key-id 1 \\
        --out node_a_gateway/bootloader/proj_cm4/src/test_signed_image.h
"""
from __future__ import annotations

import argparse
import pathlib
import sys
import textwrap

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import sign_image  # noqa: E402


def c_array(name: str, data: bytes) -> str:
    rows = textwrap.indent(
        "\n".join(
            ", ".join(f"0x{b:02X}u" for b in data[i:i + 8]) + ","
            for i in range(0, len(data), 8)
        ),
        "    ",
    )
    return f"static const uint8_t {name}[{len(data)}] = {{\n{rows}\n}};\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--key", required=True, help="dev private key PEM (from gen_dev_key.py)")
    ap.add_argument("--key-id", type=lambda x: int(x, 0), default=1)
    ap.add_argument("--out", required=True, help="C header to write")
    ap.add_argument("--header-offset", type=lambda x: int(x, 0),
                    default=sign_image.DEFAULT_HEADER_OFFSET)
    args = ap.parse_args(argv)

    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.serialization import load_pem_private_key

    with open(args.key, "rb") as f:
        dev_priv = load_pem_private_key(f.read(), password=None)

    # Deterministic 512-byte body (larger than the header offset).
    body = bytes((i * 7 + 3) & 0xFF for i in range(512))
    image_len = len(body)

    good = sign_image.sign_image(body, dev_priv, args.key_id, args.header_offset)

    tampered = bytearray(good)
    tampered[args.header_offset + 0x40] ^= 0xFF   # flip a covered body byte, after the header
    tampered = bytes(tampered)

    # Same body + same claimed key_id, but signed by a throwaway key -> must fail.
    wrong_priv = ec.generate_private_key(ec.SECP256R1())
    wrongkey = sign_image.sign_image(body, wrong_priv, args.key_id, args.header_offset)

    header = f"""\
/* GENERATED by host_tools/make_test_image.py — M4 Seam-3 bench images. DO NOT hand-edit. */
#ifndef TEST_SIGNED_IMAGE_H
#define TEST_SIGNED_IMAGE_H

#include <stdint.h>

#define TEST_IMAGE_KEY_ID   {args.key_id}u
#define TEST_IMAGE_LEN      {image_len}u   /* covered range; the {sign_image.TRAILER_SIZE}-byte trailer follows */

{c_array("test_image_good", good)}
{c_array("test_image_tampered", tampered)}
{c_array("test_image_wrongkey", wrongkey)}
#endif /* TEST_SIGNED_IMAGE_H */
"""
    with open(args.out, "w", newline="\n") as f:
        f.write(header)

    print(f"wrote {args.out}")
    print(f"  image_len={image_len} B, trailer={sign_image.TRAILER_SIZE} B, "
          f"total each={len(good)} B, key_id={args.key_id}")
    print("  expect on-board: good=VALID(1), tampered=INVALID(0), wrongkey=INVALID(0)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
