/*
 * startup_fbl.c — FBL startup (PLACEHOLDER).
 *
 * The production startup is generated by ModusToolbox for the CYT2B7 and then
 * customised; this file only records the FBL-specific customisations so the
 * intent is captured before the board arrives. Excluded from host lint/CI
 * (target-only, partly generated).
 *
 * FBL-specific customisations required (verify mechanisms in TRM):
 *   1. Vector table (.isr_vector) at the FLASH base 0x1000_0000 — the ROM hands
 *      control here after verifying the FBL (ADR-0006 root of trust).
 *   2. On COLD boot, initialise SRAM ECC by writing all of SRAM *except* the
 *      pinned `.noinit` region; prime `.noinit` separately (ADR-0007 D3). On a
 *      warm reset, leave `.noinit` untouched so the handshake survives.
 *   3. Standard .data copy / .bss zero — but NEVER zero `.noinit`.
 *   4. Set MSP from vector[0], then branch to Reset_Handler -> main().
 *
 * TODO(M1, board): replace with the MTB-generated startup carrying the above.
 */

extern int main(void);

/* Minimal reset entry placeholder. The real Reset_Handler also does ECC init,
 * .data/.bss setup, and the cold/warm .noinit handling above. */
void Reset_Handler(void)
{
    /* TODO(M1, board): SRAM ECC init (cold only), .data/.bss, .noinit handling. */
    (void)main();
    for (;;)
    {
        /* main() does not return */
    }
}
