/* GENERATED by host_tools/gen_log_events.py from shared/log/events.csv.
 * DO NOT EDIT -- edit the CSV and re-run the generator (ADR-0023 D9). */
#ifndef LOG_EVENTS_H
#define LOG_EVENTS_H

#include <stdint.h>

/* Contract events (id < LOG_EVT_DIAG_BASE) are part of the tested interface:
 * a BVT test may assert on them, and changing one is a breaking change that
 * must update the affected tests in the same commit. Diagnostic events are
 * never asserted on and stay free to add, reword or delete (REQ-LOG-008). */

#define LOG_EVT_BOOT                   0x0001U   /* contract: Image started; first record after log_init */
#define LOG_EVT_APP_JUMP               0x0002U   /* contract: FBL verified the app and is jumping (ADR-0008) */
#define LOG_EVT_APP_REJECT             0x0003U   /* contract: FBL refused to jump -- stays in FBL (fail-safe) */
#define LOG_EVT_OVERFLOW               0x0004U   /* contract: Records lost since the last overflow report (D5) */
#define LOG_EVT_SECOC_ACCEPT           0x0101U   /* contract: Secured frame accepted and actuated */
#define LOG_EVT_SECOC_REJECT_MAC       0x0102U   /* contract: MAC comparison failed -- forged or corrupt frame */
#define LOG_EVT_SECOC_REJECT_FRESHNESS 0x0103U   /* contract: Freshness not ahead of stored -- replay */
#define LOG_EVT_SECOC_RESYNC           0x0104U   /* contract: Receiver-reset resync completed (ADR-0021 D5) */
#define LOG_EVT_CRYPTO_ERROR           0x0201U   /* contract: Crypto op produced ERROR (M0+ dead/timeout/malformed) */
#define LOG_EVT_UDS_SESSION            0x0301U   /* contract: Diagnostic session changed */
#define LOG_EVT_UDS_SECURITY           0x0302U   /* contract: SecurityAccess unlock result */
#define LOG_EVT_APP_ALIVE              0x0401U   /* contract: Periodic liveness -- the BVT liveness test keys on this */
#define LOG_EVT_DBG_U32                0x1001U   /* diagnostic: Ad-hoc developer value; delete freely */
#define LOG_EVT_CRYPTO_MAC_US          0x1002U   /* diagnostic: MAC round-trip time -- timing only */

#endif /* LOG_EVENTS_H */
