# GENERATED by host_tools/gen_log_events.py from shared/log/events.csv.
# DO NOT EDIT -- edit the CSV and re-run the generator (ADR-0023 D9).
"""Event table for the host log decoder."""

CONTRACT_MAX = 0x0FFF

# id -> (name, class, arg0 meaning, arg1 meaning, description)
EVENTS = {
    0x0001: ('LOG_EVT_BOOT', 'contract', 'reset_reason', '-', 'Image started; first record after log_init. reset_reason is the CY_SYSLIB_RESET_* bitmask'),
    0x0002: ('LOG_EVT_APP_JUMP', 'contract', 'app_entry_addr', '-', 'FBL verified the app and is jumping (ADR-0008)'),
    0x0003: ('LOG_EVT_APP_REJECT', 'contract', 'fail_addr', 'reason', 'FBL refused to jump -- stays in FBL (fail-safe)'),
    0x0004: ('LOG_EVT_OVERFLOW', 'contract', 'dropped_count', '-', 'Records lost since the last overflow report (D5)'),
    0x0101: ('LOG_EVT_SECOC_ACCEPT', 'contract', 'can_id', 'freshness_ctr', 'Secured frame passed MAC + freshness and was released to decode'),
    0x0102: ('LOG_EVT_SECOC_REJECT_MAC', 'contract', 'can_id', 'reject_reason', 'MAC check failed -- forged/corrupt frame (1) bad length (2) or oracle error (3)'),
    0x0103: ('LOG_EVT_SECOC_REJECT_FRESHNESS', 'contract', 'can_id', 'rx_ctr', 'Freshness not ahead of stored -- replay'),
    0x0104: ('LOG_EVT_SECOC_RESYNC', 'contract', 'can_id', 'new_epoch', 'Receiver-reset resync completed -- sender adopted the floor (ADR-0021 D5)'),
    0x0201: ('LOG_EVT_CRYPTO_ERROR', 'contract', 'op', 'ipc_status', 'Crypto op produced ERROR (M0+ dead/timeout/malformed)'),
    0x0301: ('LOG_EVT_UDS_SESSION', 'contract', 'new_session', '-', 'Diagnostic session changed'),
    0x0302: ('LOG_EVT_UDS_SECURITY', 'contract', 'granted', 'attempt_no', 'SecurityAccess unlock result'),
    0x0401: ('LOG_EVT_APP_ALIVE', 'contract', 'uptime_ms', 'stack_free_words', 'Liveness every 5s; first is immediate after boot -- BVT timeouts must clear 5s'),
    0x1001: ('LOG_EVT_DBG_U32', 'diagnostic', 'value', 'tag', 'Ad-hoc developer value; delete freely'),
    0x1002: ('LOG_EVT_CRYPTO_MAC_US', 'diagnostic', 'elapsed_us', '-', 'MAC round-trip time -- timing only'),
}

NAME_TO_ID = {v[0]: k for k, v in EVENTS.items()}


def name(evt_id):
    """Event name, or a hex placeholder for an id this build does not know."""
    e = EVENTS.get(evt_id)
    return e[0] if e else f'EVT_{evt_id:#06x}'


def is_contract(evt_id):
    """True if a test is allowed to assert on this event (REQ-LOG-008)."""
    return evt_id <= CONTRACT_MAX
